name: Deploy Hello World Page

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your EC2 instance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build image from docker
        run: docker build -t hello-asad .

      - name: run new container
        run: |
          docker run -d -p 80:80 hello-html
