name: Deploy Hello World Page

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your EC2 instance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t hello-asad .

      - name: Run Docker container
        run: |
          docker rm -f hello-asad || true  # Optional: remove old container
          docker run -d -p 80:80 --name hello-asad hello-asad
