name: Deploy Hello World Page

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your EC2 instance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          sudo cp index.html /var/www/html/index.html
          sudo systemctl restart nginx  # or apache2 if you're using Apache
          echo "Deployment done!"
